### ISSUE TITLE
Empty arrays are parsed as undefined

### ISSUE THREAD

**Issue by oded11** [jsonurl/jsonurl-js#102]
Hi,

I found a bug parsing empty arrays.
See the example in the image bellow.

<img width="798" alt="Screen Shot 2020-11-12 at 14 10 27" src="https://user-images.githubusercontent.com/45260425/98938947-5bc09c80-24f1-11eb-94d5-68134fc1ee98.png">

**Comment by dmaccormack** [comment]
Let me first say hi and thanks for the report!

I created a notebook on RunKit: https://runkit.com/dmaccormack/jsonurl-issue-102

I added an additional log statement in there to break up the two lines. Screenshot attached showing expected output.

![jsonurl_issue_102_1](https://user-images.githubusercontent.com/35852337/98977868-1a2af400-24e7-11eb-858c-b06eaaf38f71.png)

So, I can't replicate it.

When two lines are the same RunKit will combine them and put "x2" icon on the right hand side. Maybe that's what happened and it was just chopped off on your screenshot?

**Comment by eyalw** [comment]
I'm confused, you showed a screenshot that exactly replicates the problem.
one line stringified and parsed an empty object `{}` into an empty object `{}` - Correct!
the second line stringified and parsed an empty array `[]` into an empty object `{}`, instead of an empty array `[]` - Wrong!

**Comment by dmaccormack** [comment]
Ah, I see the confusion.

Per https://github.com/jsonurl/specification/#22-composites JSON→URL does not distinguish between empty array and empty object, and instead defines an empty composite value. The JS implementation allows this value to be customized via  a parser property, though the default is just an object. What you're seeing is the default.

Here's an example of using a custom value: https://runkit.com/dmaccormack/jsonurl-issue-102-2

**Comment by eyalw** [comment]
oh this is a real bummer. so its not consistent  : /
not sure why they didn't distinguish between the too... can be done easily. `(:)` - empty object, `()` - empty array

**Comment by dmaccormack** [comment]
I'm not sure I agree with the characterization "inconsistent" but I do see how the defaut is counterintuitive. ;)

That being said I like the suggestion as a new option.

The jsonurl text (:) is equivalent to {"":""} when options.allowEmptyUnquotedKeys and options.allowEmptyUnquotedValues are enabled. But, it's a syntax error otherwise. A new option could allow that sequence to be used to distinguish between empty array and empty object.

**Comment by eyalw** [comment]
that would be really nice! +1
