### ISSUE TITLE
Resolve one or more codesmells

### ISSUE THREAD

**Issue by dmaccormack** [jsonurl/jsonurl-js#182]
Using https://sonarcloud.io/project/issues?id=jsonurl-js&resolved=false as a reference, resolve one or more codesmells.

**Comment by shoebsd31** [comment]
Hi @dmaccormack can I also work on this one ?

**Comment by dmaccormack** [comment]
> Hi @dmaccormack can I also work on this one ?

Yeah, have at it. :)

**Comment by shoebsd31** [comment]
Hi @dmaccormack , 

I am sorry I don't get time to work on this.

**Comment by dmaccormack** [comment]
> I am sorry I don't get time to work on this.
@shoebsd31 OK, no worries.
