### ISSUE TITLE
Unexpected failure with trailing !e in AQF implied array / object mode

### ISSUE THREAD

**Issue by cdleonard** [jsonurl/jsonurl-js#556]
I've been playing around with this library and encountered a weird cornercase. The following parses fail:

```
JsonURL.parse("e,!e", { AQF: true, impliedArray: [] })
JsonURL.parse("e:!e", { AQF: true, impliedObject: {} })
```

Using an explicit array/object or making sure the !e is not at the end seems to make it work.

This looks like a bug to me, am I wrong?

**Comment by dmaccormack** [comment]
Hi, @cdleonard. Confirmed, this is a bug. Thanks for the report and test cases.
