### ISSUE TITLE
Is this ready for production?

### ISSUE THREAD

**Issue by eyalw** [jsonurl/jsonurl-js#94]
Hi, amazing library.
the most beautiful format ive seen so far.
Is this ready for production?

**Comment by dmaccormack** [comment]
Hi, and thanks for the complement. Yes, the library is ready for production.

One thing I should note, that may or may not apply depending on you're use case. It was recently brought to my attention that there is an issue when storing a stringified value in a browser address bar. I've captured that in issue #96. It's mitigated but not yet solved.
